package com.vitaai.app.utils

import android.content.Context
import androidx.compose.runtime.mutableStateOf

object LanguageManager {

    val currentLanguage = mutableStateOf("es")

    fun setLanguage(context: Context, langCode: String) {
        currentLanguage.value = langCode
        val prefs = context.getSharedPreferences("vitaai_prefs", Context.MODE_PRIVATE)
        prefs.edit().putString("language", langCode).apply()
    }

    fun loadSavedLanguage(context: Context) {
        val prefs = context.getSharedPreferences("vitaai_prefs", Context.MODE_PRIVATE)
        currentLanguage.value = prefs.getString("language", "es") ?: "es"
    }

    fun t(key: String): String {
        return translations[currentLanguage.value]?.get(key)
            ?: translations["es"]?.get(key)
            ?: key
    }

    val languages = listOf(
        Triple("es", "🇪🇸", "Español"),
        Triple("en", "🇬🇧", "English"),
        Triple("zh", "🇨🇳", "中文"),
        Triple("fr", "🇫🇷", "Français"),
        Triple("pt", "🇧🇷", "Português")
    )

    private val translations = mapOf(
        "es" to mapOf(
            "app_name" to "VitaAI",
            "login" to "Iniciar sesión",
            "register" to "Registrarse",
            "email" to "Email",
            "password" to "Contraseña",
            "username" to "Nombre de usuario",
            "continue_google" to "Continuar con Google",
            "no_account" to "¿No tienes cuenta? Regístrate",
            "have_account" to "¿Ya tienes cuenta? Inicia sesión",
            "forgot_password" to "¿Olvidaste tu contraseña?",
            "good_morning" to "Buenos días 👋",
            "daily_tip" to "💡 Consejo del día",
            "today_mood" to "Estado de hoy",
            "quick_access" to "Acceso rápido",
            "my_plan" to "Mi plan de salud",
            "my_progress" to "Mi progreso",
            "nutritionist_ia" to "Nutricionista IA",
            "identify_food" to "Identificar alimento",
            "my_level" to "Mi nivel y XP",
            "settings" to "Configuración",
            "logout" to "Cerrar sesión",
            "generate_plan" to "Generar mi plan con IA 🤖",
            "update_plan" to "Actualizar plan con IA 🔄",
            "current_plan" to "🤖 Tu Plan Actual",
            "diet_plan" to "🥗 Plan de Dieta",
            "exercise_plan" to "💪 Plan de Ejercicio",
            "update_my_plan" to "🔄 Actualizar mi plan",
            "back_to_home" to "✅ Volver al inicio",
            "generating_plan" to "Analizando tu perfil y generando\ntu plan personalizado...",
            "how_are_you" to "¿Cómo te sientes hoy?",
            "mood_affects" to "Tu estado de ánimo afecta tu nutrición",
            "get_recommendation" to "✨ Obtener recomendación personalizada",
            "understood" to "¡Entendido, vamos! 💪",
            "save_today" to "Guardar hoy",
            "saving" to "Guardando...",
            "saved" to "✅ Guardado",
            "language" to "Idioma",
            "select_language" to "Seleccionar idioma",
            "change_password" to "🔒 Cambiar contraseña",
            "current_password" to "Contraseña actual",
            "new_password" to "Nueva contraseña",
            "confirm_password" to "Confirmar nueva contraseña",
            "update_password" to "Actualizar contraseña",
            "ask_me" to "Pregúntame algo...",
            "send" to "Enviar",
            "profile" to "Tu perfil",
            "tell_us" to "Cuéntanos sobre ti",
            "age" to "Edad",
            "weight" to "Peso (kg)",
            "height" to "Altura (cm)",
            "goal" to "🎯 Objetivo",
            "activity_level" to "🏃 Nivel de actividad",
            "lose_weight" to "Perder peso",
            "gain_muscle" to "Ganar músculo",
            "maintain_weight" to "Mantener peso",
            "improve_health" to "Mejorar salud",
            "sedentary" to "Sedentario",
            "light" to "Ligero",
            "moderate" to "Moderado",
            "active" to "Activo",
            "very_active" to "Muy activo"
        ),
        "en" to mapOf(
            "app_name" to "VitaAI",
            "login" to "Sign in",
            "register" to "Sign up",
            "email" to "Email",
            "password" to "Password",
            "username" to "Username",
            "continue_google" to "Continue with Google",
            "no_account" to "Don't have an account? Sign up",
            "have_account" to "Already have an account? Sign in",
            "forgot_password" to "Forgot your password?",
            "good_morning" to "Good morning 👋",
            "daily_tip" to "💡 Tip of the day",
            "today_mood" to "Today's mood",
            "quick_access" to "Quick access",
            "my_plan" to "My health plan",
            "my_progress" to "My progress",
            "nutritionist_ia" to "AI Nutritionist",
            "identify_food" to "Identify food",
            "my_level" to "My level & XP",
            "settings" to "Settings",
            "logout" to "Sign out",
            "generate_plan" to "Generate my AI plan 🤖",
            "update_plan" to "Update AI plan 🔄",
            "current_plan" to "🤖 Your Current Plan",
            "diet_plan" to "🥗 Diet Plan",
            "exercise_plan" to "💪 Exercise Plan",
            "update_my_plan" to "🔄 Update my plan",
            "back_to_home" to "✅ Back to home",
            "generating_plan" to "Analyzing your profile and generating\nyour personalized plan...",
            "how_are_you" to "How are you feeling today?",
            "mood_affects" to "Your mood affects your nutrition",
            "get_recommendation" to "✨ Get personalized recommendation",
            "understood" to "Got it, let's go! 💪",
            "save_today" to "Save today",
            "saving" to "Saving...",
            "saved" to "✅ Saved",
            "language" to "Language",
            "select_language" to "Select language",
            "change_password" to "🔒 Change password",
            "current_password" to "Current password",
            "new_password" to "New password",
            "confirm_password" to "Confirm new password",
            "update_password" to "Update password",
            "ask_me" to "Ask me something...",
            "send" to "Send",
            "profile" to "Your profile",
            "tell_us" to "Tell us about yourself",
            "age" to "Age",
            "weight" to "Weight (kg)",
            "height" to "Height (cm)",
            "goal" to "🎯 Goal",
            "activity_level" to "🏃 Activity level",
            "lose_weight" to "Lose weight",
            "gain_muscle" to "Gain muscle",
            "maintain_weight" to "Maintain weight",
            "improve_health" to "Improve health",
            "sedentary" to "Sedentary",
            "light" to "Light",
            "moderate" to "Moderate",
            "active" to "Active",
            "very_active" to "Very active"
        ),
        "zh" to mapOf(
            "app_name" to "VitaAI",
            "login" to "登录",
            "register" to "注册",
            "email" to "邮箱",
            "password" to "密码",
            "username" to "用户名",
            "continue_google" to "使用Google登录",
            "no_account" to "没有账号？立即注册",
            "have_account" to "已有账号？立即登录",
            "forgot_password" to "忘记密码？",
            "good_morning" to "早上好 👋",
            "daily_tip" to "💡 每日健康提示",
            "today_mood" to "今日状态",
            "quick_access" to "快速访问",
            "my_plan" to "我的健康计划",
            "my_progress" to "我的进度",
            "nutritionist_ia" to "AI营养师",
            "identify_food" to "识别食物",
            "my_level" to "我的等级和经验",
            "settings" to "设置",
            "logout" to "退出登录",
            "generate_plan" to "用AI生成我的计划 🤖",
            "update_plan" to "更新AI计划 🔄",
            "current_plan" to "🤖 你的当前计划",
            "diet_plan" to "🥗 饮食计划",
            "exercise_plan" to "💪 运动计划",
            "update_my_plan" to "🔄 更新我的计划",
            "back_to_home" to "✅ 返回首页",
            "generating_plan" to "正在分析你的资料并生成\n个性化计划...",
            "how_are_you" to "今天感觉怎么样？",
            "mood_affects" to "你的情绪影响你的营养",
            "get_recommendation" to "✨ 获取个性化建议",
            "understood" to "明白了，出发！💪",
            "save_today" to "保存今天",
            "saving" to "保存中...",
            "saved" to "✅ 已保存",
            "language" to "语言",
            "select_language" to "选择语言",
            "change_password" to "🔒 修改密码",
            "current_password" to "当前密码",
            "new_password" to "新密码",
            "confirm_password" to "确认新密码",
            "update_password" to "更新密码",
            "ask_me" to "问我任何问题...",
            "send" to "发送",
            "profile" to "你的资料",
            "tell_us" to "告诉我们关于你的信息",
            "age" to "年龄",
            "weight" to "体重 (kg)",
            "height" to "身高 (cm)",
            "goal" to "🎯 目标",
            "activity_level" to "🏃 活动水平",
            "lose_weight" to "减重",
            "gain_muscle" to "增肌",
            "maintain_weight" to "保持体重",
            "improve_health" to "改善健康",
            "sedentary" to "久坐",
            "light" to "轻度",
            "moderate" to "中度",
            "active" to "活跃",
            "very_active" to "非常活跃"
        ),
        "fr" to mapOf(
            "app_name" to "VitaAI",
            "login" to "Se connecter",
            "register" to "S'inscrire",
            "email" to "Email",
            "password" to "Mot de passe",
            "username" to "Nom d'utilisateur",
            "continue_google" to "Continuer avec Google",
            "no_account" to "Pas de compte ? S'inscrire",
            "have_account" to "Déjà un compte ? Se connecter",
            "forgot_password" to "Mot de passe oublié ?",
            "good_morning" to "Bonjour 👋",
            "daily_tip" to "💡 Conseil du jour",
            "today_mood" to "Humeur du jour",
            "quick_access" to "Accès rapide",
            "my_plan" to "Mon plan santé",
            "my_progress" to "Ma progression",
            "nutritionist_ia" to "Nutritionniste IA",
            "identify_food" to "Identifier l'aliment",
            "my_level" to "Mon niveau et XP",
            "settings" to "Paramètres",
            "logout" to "Se déconnecter",
            "generate_plan" to "Générer mon plan IA 🤖",
            "update_plan" to "Mettre à jour le plan IA 🔄",
            "current_plan" to "🤖 Votre Plan Actuel",
            "diet_plan" to "🥗 Plan Alimentaire",
            "exercise_plan" to "💪 Plan d'Exercice",
            "update_my_plan" to "🔄 Mettre à jour mon plan",
            "back_to_home" to "✅ Retour à l'accueil",
            "generating_plan" to "Analyse de votre profil et génération\nde votre plan personnalisé...",
            "how_are_you" to "Comment vous sentez-vous aujourd'hui ?",
            "mood_affects" to "Votre humeur affecte votre nutrition",
            "get_recommendation" to "✨ Obtenir une recommandation personnalisée",
            "understood" to "Compris, allons-y ! 💪",
            "save_today" to "Enregistrer aujourd'hui",
            "saving" to "Enregistrement...",
            "saved" to "✅ Enregistré",
            "language" to "Langue",
            "select_language" to "Sélectionner la langue",
            "change_password" to "🔒 Changer le mot de passe",
            "current_password" to "Mot de passe actuel",
            "new_password" to "Nouveau mot de passe",
            "confirm_password" to "Confirmer le nouveau mot de passe",
            "update_password" to "Mettre à jour le mot de passe",
            "ask_me" to "Posez-moi une question...",
            "send" to "Envoyer",
            "profile" to "Votre profil",
            "tell_us" to "Parlez-nous de vous",
            "age" to "Âge",
            "weight" to "Poids (kg)",
            "height" to "Taille (cm)",
            "goal" to "🎯 Objectif",
            "activity_level" to "🏃 Niveau d'activité",
            "lose_weight" to "Perdre du poids",
            "gain_muscle" to "Gagner du muscle",
            "maintain_weight" to "Maintenir le poids",
            "improve_health" to "Améliorer la santé",
            "sedentary" to "Sédentaire",
            "light" to "Léger",
            "moderate" to "Modéré",
            "active" to "Actif",
            "very_active" to "Très actif"
        ),
        "pt" to mapOf(
            "app_name" to "VitaAI",
            "login" to "Entrar",
            "register" to "Registrar",
            "email" to "Email",
            "password" to "Senha",
            "username" to "Nome de usuário",
            "continue_google" to "Continuar com Google",
            "no_account" to "Não tem conta? Registre-se",
            "have_account" to "Já tem conta? Entre",
            "forgot_password" to "Esqueceu a senha?",
            "good_morning" to "Bom dia 👋",
            "daily_tip" to "💡 Dica do dia",
            "today_mood" to "Humor de hoje",
            "quick_access" to "Acesso rápido",
            "my_plan" to "Meu plano de saúde",
            "my_progress" to "Meu progresso",
            "nutritionist_ia" to "Nutricionista IA",
            "identify_food" to "Identificar alimento",
            "my_level" to "Meu nível e XP",
            "settings" to "Configurações",
            "logout" to "Sair",
            "generate_plan" to "Gerar meu plano com IA 🤖",
            "update_plan" to "Atualizar plano com IA 🔄",
            "current_plan" to "🤖 Seu Plano Atual",
            "diet_plan" to "🥗 Plano Alimentar",
            "exercise_plan" to "💪 Plano de Exercícios",
            "update_my_plan" to "🔄 Atualizar meu plano",
            "back_to_home" to "✅ Voltar ao início",
            "generating_plan" to "Analisando seu perfil e gerando\nseu plano personalizado...",
            "how_are_you" to "Como você está hoje?",
            "mood_affects" to "Seu humor afeta sua nutrição",
            "get_recommendation" to "✨ Obter recomendação personalizada",
            "understood" to "Entendido, vamos! 💪",
            "save_today" to "Salvar hoje",
            "saving" to "Salvando...",
            "saved" to "✅ Salvo",
            "language" to "Idioma",
            "select_language" to "Selecionar idioma",
            "change_password" to "🔒 Alterar senha",
            "current_password" to "Senha atual",
            "new_password" to "Nova senha",
            "confirm_password" to "Confirmar nova senha",
            "update_password" to "Atualizar senha",
            "ask_me" to "Me pergunte algo...",
            "send" to "Enviar",
            "profile" to "Seu perfil",
            "tell_us" to "Conte-nos sobre você",
            "age" to "Idade",
            "weight" to "Peso (kg)",
            "height" to "Altura (cm)",
            "goal" to "🎯 Objetivo",
            "activity_level" to "🏃 Nível de atividade",
            "lose_weight" to "Perder peso",
            "gain_muscle" to "Ganhar músculo",
            "maintain_weight" to "Manter peso",
            "improve_health" to "Melhorar saúde",
            "sedentary" to "Sedentário",
            "light" to "Leve",
            "moderate" to "Moderado",
            "active" to "Ativo",
            "very_active" to "Muito ativo"
        )
    )
}