package com.vitaai.app.utils

import android.content.Context
import androidx.compose.runtime.mutableStateOf

object LanguageManager {

    val currentLanguage = mutableStateOf("es")

    fun setLanguage(context: Context, langCode: String) {
        currentLanguage.value = langCode
        val prefs = context.getSharedPreferences("vitaai_prefs", Context.MODE_PRIVATE)
        prefs.edit().putString("language", langCode).apply()
    }

    fun loadSavedLanguage(context: Context) {
        val prefs = context.getSharedPreferences("vitaai_prefs", Context.MODE_PRIVATE)
        currentLanguage.value = prefs.getString("language", "es") ?: "es"
    }

    fun t(key: String): String {
        return translations[currentLanguage.value]?.get(key)
            ?: translations["es"]?.get(key)
            ?: key
    }

    val languages = listOf(
        Triple("es", "🇪🇸", "Español"),
        Triple("en", "🇬🇧", "English"),
        Triple("zh", "🇨🇳", "中文"),
        Triple("fr", "🇫🇷", "Français"),
        Triple("pt", "🇧🇷", "Português")
    )

    private val translations = mapOf(
        "es" to mapOf(
            "app_name" to "VitaAI",
            "login" to "Iniciar sesión",
            "register" to "Registrarse",
            "email" to "Email",
            "password" to "Contraseña",
            "username" to "Nombre de usuario",
            "continue_google" to "Continuar con Google",
            "no_account" to "¿No tienes cuenta? Regístrate",
            "have_account" to "¿Ya tienes cuenta? Inicia sesión",
            "forgot_password" to "¿Olvidaste tu contraseña?",
            "good_morning" to "Buenos días 👋",
            "daily_tip" to "💡 Consejo del día",
            "today_mood" to "Estado de hoy",
            "quick_access" to "Acceso rápido",
            "my_plan" to "Mi plan de salud",
            "my_progress" to "Mi progreso",
            "nutritionist_ia" to "Nutricionista IA",
            "identify_food" to "Identificar alimento",
            "my_level" to "Mi nivel y XP",
            "more" to "Más",
            "settings" to "Configuración",
            "logout" to "Cerrar sesión",
            "generate_plan" to "Generar mi plan con IA 🤖",
            "update_plan" to "Actualizar plan con IA 🔄",
            "current_plan" to "🤖 Tu Plan Actual",
            "diet_plan" to "🥗 Plan de Dieta",
            "exercise_plan" to "💪 Plan de Ejercicio",
            "update_my_plan" to "🔄 Actualizar mi plan",
            "back_to_home" to "✅ Volver al inicio",
            "generating_plan" to "Analizando tu perfil y generando\ntu plan personalizado...",
            "how_are_you" to "¿Cómo te sientes hoy?",
            "mood_affects" to "Tu estado de ánimo afecta tu nutrición",
            "get_recommendation" to "✨ Obtener recomendación personalizada",
            "understood" to "¡Entendido, vamos! 💪",
            "save_today" to "Guardar hoy",
            "saving" to "Guardando...",
            "saved" to "✅ Guardado",
            "language" to "Idioma",
            "select_language" to "Seleccionar idioma",
            "change_password" to "🔒 Cambiar contraseña",
            "current_password" to "Contraseña actual",
            "new_password" to "Nueva contraseña",
            "confirm_password" to "Confirmar nueva contraseña",
            "update_password" to "Actualizar contraseña",
            "ask_me" to "Pregúntame algo...",
            "send" to "Enviar",
            "profile" to "Tu perfil",
            "tell_us" to "Cuéntanos sobre ti",
            "age" to "Edad",
            "weight" to "Peso (kg)",
            "height" to "Altura (cm)",
            "goal" to "🎯 Objetivo",
            "activity_level" to "🏃 Nivel de actividad",
            "lose_weight" to "Perder peso",
            "gain_muscle" to "Ganar músculo",
            "maintain_weight" to "Mantener peso",
            "improve_health" to "Mejorar salud",
            "sedentary" to "Sedentario",
            "light" to "Ligero",
            "moderate" to "Moderado",
            "active" to "Activo",
            "very_active" to "Muy activo",
            "loading_plan" to "Cargando tu plan...",
            "saved_plan" to "Tu plan personalizado guardado",
            "update_profile" to "Actualizar tu perfil",
            "see_current_plan" to "← Ver plan actual",
            "point_at_food" to "Apunta al alimento",
            "nutritional_analysis" to "Análisis nutricional",
            "ai_result" to "Resultado de IA",
            "save_to_log" to "Guardar en mi registro",
            "take_another_photo" to "Tomar otra foto",
            "camera_permission_required" to "Se requiere acceso a la cámara para identificar alimentos",
            "grant_permission" to "Conceder permiso",
            "error_analyzing" to "Error al analizar",
            "xp_daily_limit_food" to "máximo 3 fotos con XP por día",
            "chat_error" to "Lo siento, hubo un error. Por favor intenta de nuevo.",
            "level_beginner" to "Principiante",
            "level_apprentice" to "Aprendiz",
            "level_athlete" to "Atleta",
            "level_expert" to "Experto",
            "level_master" to "Maestro",
            "level" to "Nivel",
            "xp_to_next" to "Faltan {xp} XP para el siguiente nivel",
            "max_level_reached" to "¡Nivel máximo alcanzado! 🎉",
            "how_to_earn_xp" to "Cómo ganar XP",
            "xp_action_progress" to "Registrar progreso diario",
            "xp_action_plan" to "Generar plan con IA",
            "xp_action_food" to "Identificar alimento",
            "xp_action_chat" to "Chatear con nutricionista",
            "xp_action_mood" to "Registrar estado de ánimo",
            "all_levels" to "Todos los niveles",
            "from_xp" to "Desde {xp} XP",
            "current" to "ACTUAL",
            "today_log" to "Registro de hoy",
            "calories" to "Calorías",
            "xp_already_claimed_today" to "XP ya reclamado hoy",
            "weight_evolution" to "Evolución del peso",
            "weight_short" to "Peso",
            "daily_calories" to "Calorías diarias",
            "no_data_yet" to "Aún no hay datos.\n¡Registra tu primer día! 💪",
            "water_tracker" to "Hidratación",
            "food_history" to "Historial de comidas",
            "my_goals" to "Mis objetivos",
            "achievements" to "Logros",
            "exercise_log" to "Ejercicio",
            "weekly_report" to "Informe semanal",
            "bmr_calculator" to "Calculadora BMR",
            "today_nutrition" to "Nutrición de hoy",
            "quick_add" to "Añadir rápido",
            "reset_today" to "Reiniciar hoy",
            "now" to "Ahora",
            "start" to "Inicio",
            "current_goal" to "Objetivo actual",
            "set_goal" to "Definir objetivo",
            "save_goal" to "Guardar objetivo",
            "save" to "Guardar",
            "target_weight" to "Peso objetivo (kg)",
            "target_date_hint" to "Fecha objetivo",
            "days_left" to "Quedan {days} días",
            "unlocked" to "Desbloqueados",
            "no_food_yet" to "Aún no has registrado comidas",
            "analyzing_week" to "Analizando tu semana...",
            "regenerate" to "Regenerar",
            "no_week_data" to "Necesitas datos de los últimos 7 días para generar el informe",
            "bmi" to "IMC",
            "bmi_underweight" to "Bajo peso",
            "bmi_normal" to "Peso saludable",
            "bmi_overweight" to "Sobrepeso",
            "bmi_obese" to "Obesidad",
            "bmr_explain" to "Calorías en reposo",
            "tdee_explain" to "Gasto diario total",
            "recommended_targets" to "Objetivos recomendados",
            "protein" to "Proteínas",
            "carbs" to "Carbohidratos",
            "fat" to "Grasas",
            "water" to "Agua",
            "theme" to "Tema",
            "theme_system" to "Sistema",
            "theme_light" to "Claro",
            "theme_dark" to "Oscuro",
            "notifications" to "Notificaciones",
            "notif_water_title" to "Hora de hidratarte",
            "notif_water_body" to "💧 Bebe un vaso de agua y mantén tu meta diaria",
            "notif_water_desc" to "Recordatorios cada 3 horas",
            "notif_evening_title" to "Registra tu día",
            "notif_evening_body" to "🌙 Anota tu peso, calorías y estado de ánimo",
            "notif_evening_desc" to "Cada noche a las 20:00",
            "bmr_subtitle" to "BMR, TDEE y macros recomendados",
            "my_account" to "Mi cuenta",
            "pwd_no_match" to "Las contraseñas no coinciden",
            "pwd_too_short" to "La contraseña debe tener al menos 6 caracteres",
            "pwd_update_failed" to "Error al actualizar contraseña",
            "pwd_wrong_current" to "Contraseña actual incorrecta",
            "choose_exercise" to "Elige un ejercicio",
            "duration_min" to "Duración (min)",
            "recent_history" to "Historial reciente",
            "ex_walking" to "Caminar",
            "ex_running" to "Correr",
            "ex_cycling" to "Ciclismo",
            "ex_swimming" to "Nadar",
            "ex_yoga" to "Yoga",
            "ex_gym" to "Gimnasio",
            "ex_dance" to "Bailar",
            "ex_hiit" to "HIIT",
            "ach_first_plan_t" to "Primer plan",
            "ach_first_plan_d" to "Genera tu primer plan con IA",
            "ach_first_food_t" to "Primer escaneo",
            "ach_first_food_d" to "Identifica tu primer alimento",
            "ach_first_chat_t" to "Primera consulta",
            "ach_first_chat_d" to "Habla con el nutricionista IA",
            "ach_first_mood_t" to "Primer ánimo",
            "ach_first_mood_d" to "Registra cómo te sientes",
            "ach_first_water_t" to "Hidratación",
            "ach_first_water_d" to "Registra tu primer vaso de agua",
            "ach_first_exercise_t" to "Primer ejercicio",
            "ach_first_exercise_d" to "Registra una sesión de ejercicio",
            "ach_streak3_t" to "Racha de 3",
            "ach_streak3_d" to "3 días seguidos activo",
            "ach_streak7_t" to "Racha de 7",
            "ach_streak7_d" to "Una semana entera sin fallar",
            "ach_streak30_t" to "Racha de 30",
            "ach_streak30_d" to "30 días seguidos. Imparable",
            "ach_water_goal_t" to "Meta de agua",
            "ach_water_goal_d" to "Cumple tu meta diaria de agua",
            "ach_food10_t" to "10 comidas",
            "ach_food10_d" to "Escanea 10 alimentos",
            "ach_food50_t" to "50 comidas",
            "ach_food50_d" to "Escanea 50 alimentos",
            "ach_level3_t" to "Atleta",
            "ach_level3_d" to "Alcanza el nivel 3",
            "ach_level5_t" to "Maestro",
            "ach_level5_d" to "Alcanza el nivel máximo",
            "ach_goal_t" to "Meta alcanzada",
            "ach_goal_d" to "Llega a tu peso objetivo",
            "today" to "Hoy",
            "yesterday" to "Ayer",
            "add_food" to "Añadir comida",
            "food_name" to "Nombre del alimento",
            "cancel" to "Cancelar",
            "error_saving" to "Error al guardar: ",
            "daily_challenge" to "Reto del día",
            "challenge_completed" to "¡Reto completado!",
            "mark_complete" to "Marcar completado",
            "ch_water_2l_t" to "Bebe 2L de agua",
            "ch_water_2l_d" to "Alcanza al menos 2000ml hoy",
            "ch_scan_food_t" to "Escanea 3 alimentos",
            "ch_scan_food_d" to "Usa la cámara IA con 3 comidas hoy",
            "ch_chat_t" to "Consulta a la IA",
            "ch_chat_d" to "Pregunta algo al nutricionista IA",
            "ch_log_weight_t" to "Pésate",
            "ch_log_weight_d" to "Registra tu peso de hoy",
            "ch_exercise_t" to "30 minutos de movimiento",
            "ch_exercise_d" to "Registra al menos 30 min de ejercicio",
            "ch_mood_t" to "Registra tu ánimo",
            "ch_mood_d" to "Cuéntale a VitaAI cómo te sientes",
            "ch_3_meals_t" to "3 comidas balanceadas",
            "ch_3_meals_d" to "Desayuno, almuerzo y cena registrados",
            "ch_no_sugar_t" to "Día sin azúcar añadido",
            "ch_no_sugar_d" to "Evita postres y bebidas azucaradas",
            "ch_walk_5k_t" to "Camina 5000 pasos",
            "ch_walk_5k_d" to "Mueve el cuerpo todo el día",
            "ch_protein_t" to "Llega a tu proteína",
            "ch_protein_d" to "Alcanza tu objetivo diario de proteína",
            "meal_planner" to "Plan de comidas IA",
            "meal_planner_subtitle" to "Comidas personalizadas según tus macros restantes",
            "generating_meals" to "Diseñando tus comidas...",
            "meal_breakfast" to "Desayuno",
            "meal_lunch" to "Almuerzo",
            "meal_dinner" to "Cena",
            "meal_snack" to "Snack",
            "log_meal" to "Registrar comida",
            "favorites" to "Favoritos",
            "favorites_subtitle" to "Comidas frecuentes con un toque",
            "add_favorite" to "Añadir favorito",
            "log" to "Registrar",
            "no_favorites" to "Aún no tienes favoritos",
            "monthly_stats" to "Estadísticas del mes",
            "last_30_days" to "Últimos 30 días",
            "avg_calories" to "kcal promedio",
            "active_days" to "Días activos",
            "total_exercise" to "Ejercicio total",
            "weight_change" to "Cambio de peso",
            "vitals" to "Signos vitales",
            "vitals_subtitle" to "Lleva un control completo de tu salud",
            "log_today_vitals" to "Registrar hoy",
            "body_fat_pct" to "% Grasa corporal",
            "bp_sys" to "Sistólica",
            "bp_dia" to "Diastólica",
            "sleep_hours" to "Horas de sueño",
            "resting_hr" to "FC reposo",
            "shopping_list" to "Lista de compras",
            "generating_list" to "Generando tu lista...",
            "shop_cat_produce" to "🥬 Frutas y verduras",
            "shop_cat_protein" to "🥩 Proteínas",
            "shop_cat_dairy" to "🥛 Lácteos",
            "shop_cat_grains" to "🌾 Granos",
            "shop_cat_pantry" to "🥫 Despensa",
            "shop_cat_other" to "📦 Otros",
            "recipes" to "Recetas IA",
            "recipes_subtitle" to "Cocina con lo que tienes en casa",
            "available_ingredients" to "Ingredientes que tienes",
            "ingredients_example" to "ej: pollo, arroz, brócoli, ajo, aceite de oliva",
            "generate_recipes" to "Generar recetas 🍳",
            "generating_recipes" to "Pensando recetas...",
            "ingredients" to "Ingredientes",
            "steps" to "Pasos",
            "view_recipe" to "Ver receta",
            "collapse" to "Cerrar",
            "diff_easy" to "Fácil",
            "diff_medium" to "Media",
            "diff_hard" to "Difícil"
        ),
        "en" to mapOf(
            "app_name" to "VitaAI",
            "login" to "Sign in",
            "register" to "Sign up",
            "email" to "Email",
            "password" to "Password",
            "username" to "Username",
            "continue_google" to "Continue with Google",
            "no_account" to "Don't have an account? Sign up",
            "have_account" to "Already have an account? Sign in",
            "forgot_password" to "Forgot your password?",
            "good_morning" to "Good morning 👋",
            "daily_tip" to "💡 Tip of the day",
            "today_mood" to "Today's mood",
            "quick_access" to "Quick access",
            "my_plan" to "My health plan",
            "my_progress" to "My progress",
            "nutritionist_ia" to "AI Nutritionist",
            "identify_food" to "Identify food",
            "my_level" to "My level & XP",
            "more" to "More",
            "settings" to "Settings",
            "logout" to "Sign out",
            "generate_plan" to "Generate my AI plan 🤖",
            "update_plan" to "Update AI plan 🔄",
            "current_plan" to "🤖 Your Current Plan",
            "diet_plan" to "🥗 Diet Plan",
            "exercise_plan" to "💪 Exercise Plan",
            "update_my_plan" to "🔄 Update my plan",
            "back_to_home" to "✅ Back to home",
            "generating_plan" to "Analyzing your profile and generating\nyour personalized plan...",
            "how_are_you" to "How are you feeling today?",
            "mood_affects" to "Your mood affects your nutrition",
            "get_recommendation" to "✨ Get personalized recommendation",
            "understood" to "Got it, let's go! 💪",
            "save_today" to "Save today",
            "saving" to "Saving...",
            "saved" to "✅ Saved",
            "language" to "Language",
            "select_language" to "Select language",
            "change_password" to "🔒 Change password",
            "current_password" to "Current password",
            "new_password" to "New password",
            "confirm_password" to "Confirm new password",
            "update_password" to "Update password",
            "ask_me" to "Ask me something...",
            "send" to "Send",
            "profile" to "Your profile",
            "tell_us" to "Tell us about yourself",
            "age" to "Age",
            "weight" to "Weight (kg)",
            "height" to "Height (cm)",
            "goal" to "🎯 Goal",
            "activity_level" to "🏃 Activity level",
            "lose_weight" to "Lose weight",
            "gain_muscle" to "Gain muscle",
            "maintain_weight" to "Maintain weight",
            "improve_health" to "Improve health",
            "sedentary" to "Sedentary",
            "light" to "Light",
            "moderate" to "Moderate",
            "active" to "Active",
            "very_active" to "Very active",
            "loading_plan" to "Loading your plan...",
            "saved_plan" to "Your saved personalized plan",
            "update_profile" to "Update your profile",
            "see_current_plan" to "← View current plan",
            "point_at_food" to "Point at food",
            "nutritional_analysis" to "Nutritional analysis",
            "ai_result" to "AI Result",
            "save_to_log" to "Save to my log",
            "take_another_photo" to "Take another photo",
            "camera_permission_required" to "Camera access is required to identify food",
            "grant_permission" to "Grant permission",
            "error_analyzing" to "Error analyzing",
            "xp_daily_limit_food" to "max 3 photos with XP per day",
            "chat_error" to "Sorry, there was an error. Please try again.",
            "level_beginner" to "Beginner",
            "level_apprentice" to "Apprentice",
            "level_athlete" to "Athlete",
            "level_expert" to "Expert",
            "level_master" to "Master",
            "level" to "Level",
            "xp_to_next" to "{xp} XP to the next level",
            "max_level_reached" to "Max level reached! 🎉",
            "how_to_earn_xp" to "How to earn XP",
            "xp_action_progress" to "Log daily progress",
            "xp_action_plan" to "Generate AI plan",
            "xp_action_food" to "Identify food",
            "xp_action_chat" to "Chat with nutritionist",
            "xp_action_mood" to "Log mood",
            "all_levels" to "All levels",
            "from_xp" to "From {xp} XP",
            "current" to "CURRENT",
            "today_log" to "Today's log",
            "calories" to "Calories",
            "xp_already_claimed_today" to "XP already claimed today",
            "weight_evolution" to "Weight evolution",
            "weight_short" to "Weight",
            "daily_calories" to "Daily calories",
            "no_data_yet" to "No data yet.\nLog your first day! 💪",
            "water_tracker" to "Hydration",
            "food_history" to "Food history",
            "my_goals" to "My goals",
            "achievements" to "Achievements",
            "exercise_log" to "Exercise",
            "weekly_report" to "Weekly report",
            "bmr_calculator" to "BMR calculator",
            "today_nutrition" to "Today's nutrition",
            "quick_add" to "Quick add",
            "reset_today" to "Reset today",
            "now" to "Now",
            "start" to "Start",
            "current_goal" to "Current goal",
            "set_goal" to "Set goal",
            "save_goal" to "Save goal",
            "save" to "Save",
            "target_weight" to "Target weight (kg)",
            "target_date_hint" to "Target date",
            "days_left" to "{days} days left",
            "unlocked" to "Unlocked",
            "no_food_yet" to "No food logged yet",
            "analyzing_week" to "Analyzing your week...",
            "regenerate" to "Regenerate",
            "no_week_data" to "Log some data this week to generate the report",
            "bmi" to "BMI",
            "bmi_underweight" to "Underweight",
            "bmi_normal" to "Healthy weight",
            "bmi_overweight" to "Overweight",
            "bmi_obese" to "Obesity",
            "bmr_explain" to "Resting calories",
            "tdee_explain" to "Daily energy expenditure",
            "recommended_targets" to "Recommended targets",
            "protein" to "Protein",
            "carbs" to "Carbs",
            "fat" to "Fat",
            "water" to "Water",
            "theme" to "Theme",
            "theme_system" to "System",
            "theme_light" to "Light",
            "theme_dark" to "Dark",
            "notifications" to "Notifications",
            "notif_water_title" to "Time to hydrate",
            "notif_water_body" to "💧 Drink a glass of water and stay on track",
            "notif_water_desc" to "Reminders every 3 hours",
            "notif_evening_title" to "Log your day",
            "notif_evening_body" to "🌙 Record your weight, calories and mood",
            "notif_evening_desc" to "Every night at 8 PM",
            "bmr_subtitle" to "BMR, TDEE & recommended macros",
            "my_account" to "My account",
            "pwd_no_match" to "Passwords don't match",
            "pwd_too_short" to "Password must be at least 6 characters",
            "pwd_update_failed" to "Failed to update password",
            "pwd_wrong_current" to "Current password is incorrect",
            "choose_exercise" to "Pick an exercise",
            "duration_min" to "Duration (min)",
            "recent_history" to "Recent history",
            "ex_walking" to "Walking",
            "ex_running" to "Running",
            "ex_cycling" to "Cycling",
            "ex_swimming" to "Swimming",
            "ex_yoga" to "Yoga",
            "ex_gym" to "Gym",
            "ex_dance" to "Dance",
            "ex_hiit" to "HIIT",
            "ach_first_plan_t" to "First plan",
            "ach_first_plan_d" to "Generate your first AI plan",
            "ach_first_food_t" to "First scan",
            "ach_first_food_d" to "Identify your first food",
            "ach_first_chat_t" to "First chat",
            "ach_first_chat_d" to "Talk to the AI nutritionist",
            "ach_first_mood_t" to "First mood",
            "ach_first_mood_d" to "Log how you feel",
            "ach_first_water_t" to "Hydration",
            "ach_first_water_d" to "Log your first glass of water",
            "ach_first_exercise_t" to "First workout",
            "ach_first_exercise_d" to "Log an exercise session",
            "ach_streak3_t" to "3-day streak",
            "ach_streak3_d" to "3 active days in a row",
            "ach_streak7_t" to "7-day streak",
            "ach_streak7_d" to "A whole week without missing",
            "ach_streak30_t" to "30-day streak",
            "ach_streak30_d" to "30 days straight. Unstoppable",
            "ach_water_goal_t" to "Water goal",
            "ach_water_goal_d" to "Hit your daily water target",
            "ach_food10_t" to "10 meals",
            "ach_food10_d" to "Scan 10 foods",
            "ach_food50_t" to "50 meals",
            "ach_food50_d" to "Scan 50 foods",
            "ach_level3_t" to "Athlete",
            "ach_level3_d" to "Reach level 3",
            "ach_level5_t" to "Master",
            "ach_level5_d" to "Reach the max level",
            "ach_goal_t" to "Goal reached",
            "ach_goal_d" to "Hit your target weight",
            "today" to "Today",
            "yesterday" to "Yesterday",
            "add_food" to "Add food",
            "food_name" to "Food name",
            "cancel" to "Cancel",
            "error_saving" to "Save error: ",
            "daily_challenge" to "Today's challenge",
            "challenge_completed" to "Challenge completed!",
            "mark_complete" to "Mark as done",
            "ch_water_2l_t" to "Drink 2L of water",
            "ch_water_2l_d" to "Hit at least 2000ml today",
            "ch_scan_food_t" to "Scan 3 foods",
            "ch_scan_food_d" to "Use the AI camera on 3 meals today",
            "ch_chat_t" to "Ask the AI",
            "ch_chat_d" to "Send one message to the AI nutritionist",
            "ch_log_weight_t" to "Weigh yourself",
            "ch_log_weight_d" to "Log today's weight",
            "ch_exercise_t" to "30 minutes of movement",
            "ch_exercise_d" to "Log at least 30 minutes of exercise",
            "ch_mood_t" to "Log your mood",
            "ch_mood_d" to "Tell VitaAI how you're feeling",
            "ch_3_meals_t" to "3 balanced meals",
            "ch_3_meals_d" to "Breakfast, lunch and dinner logged",
            "ch_no_sugar_t" to "No added sugar today",
            "ch_no_sugar_d" to "Skip sweets and sugary drinks",
            "ch_walk_5k_t" to "Walk 5,000 steps",
            "ch_walk_5k_d" to "Keep moving throughout the day",
            "ch_protein_t" to "Hit your protein goal",
            "ch_protein_d" to "Reach your daily protein target",
            "meal_planner" to "AI meal planner",
            "meal_planner_subtitle" to "Meals tailored to your remaining macros",
            "generating_meals" to "Designing your meals...",
            "meal_breakfast" to "Breakfast",
            "meal_lunch" to "Lunch",
            "meal_dinner" to "Dinner",
            "meal_snack" to "Snack",
            "log_meal" to "Log meal",
            "favorites" to "Favorites",
            "favorites_subtitle" to "Quick-log meals you eat often",
            "add_favorite" to "Add favorite",
            "log" to "Log",
            "no_favorites" to "No favorites yet",
            "monthly_stats" to "Monthly stats",
            "last_30_days" to "Last 30 days",
            "avg_calories" to "avg kcal",
            "active_days" to "Active days",
            "total_exercise" to "Total exercise",
            "weight_change" to "Weight change",
            "vitals" to "Vitals",
            "vitals_subtitle" to "Track your full health picture",
            "log_today_vitals" to "Log today",
            "body_fat_pct" to "Body fat %",
            "bp_sys" to "Systolic",
            "bp_dia" to "Diastolic",
            "sleep_hours" to "Sleep hours",
            "resting_hr" to "Resting HR",
            "shopping_list" to "Shopping list",
            "generating_list" to "Generating your list...",
            "shop_cat_produce" to "🥬 Produce",
            "shop_cat_protein" to "🥩 Protein",
            "shop_cat_dairy" to "🥛 Dairy",
            "shop_cat_grains" to "🌾 Grains",
            "shop_cat_pantry" to "🥫 Pantry",
            "shop_cat_other" to "📦 Other",
            "recipes" to "AI recipes",
            "recipes_subtitle" to "Cook with what you've got at home",
            "available_ingredients" to "Ingredients you have",
            "ingredients_example" to "e.g. chicken, rice, broccoli, garlic, olive oil",
            "generate_recipes" to "Generate recipes 🍳",
            "generating_recipes" to "Thinking up recipes...",
            "ingredients" to "Ingredients",
            "steps" to "Steps",
            "view_recipe" to "View recipe",
            "collapse" to "Collapse",
            "diff_easy" to "Easy",
            "diff_medium" to "Medium",
            "diff_hard" to "Hard"
        ),
        "zh" to mapOf(
            "app_name" to "VitaAI",
            "login" to "登录",
            "register" to "注册",
            "email" to "邮箱",
            "password" to "密码",
            "username" to "用户名",
            "continue_google" to "使用Google登录",
            "no_account" to "没有账号？立即注册",
            "have_account" to "已有账号？立即登录",
            "forgot_password" to "忘记密码？",
            "good_morning" to "早上好 👋",
            "daily_tip" to "💡 每日健康提示",
            "today_mood" to "今日状态",
            "quick_access" to "快速访问",
            "my_plan" to "我的健康计划",
            "my_progress" to "我的进度",
            "nutritionist_ia" to "AI营养师",
            "identify_food" to "识别食物",
            "my_level" to "我的等级和经验",
            "more" to "更多",
            "settings" to "设置",
            "logout" to "退出登录",
            "generate_plan" to "用AI生成我的计划 🤖",
            "update_plan" to "更新AI计划 🔄",
            "current_plan" to "🤖 你的当前计划",
            "diet_plan" to "🥗 饮食计划",
            "exercise_plan" to "💪 运动计划",
            "update_my_plan" to "🔄 更新我的计划",
            "back_to_home" to "✅ 返回首页",
            "generating_plan" to "正在分析你的资料并生成\n个性化计划...",
            "how_are_you" to "今天感觉怎么样？",
            "mood_affects" to "你的情绪影响你的营养",
            "get_recommendation" to "✨ 获取个性化建议",
            "understood" to "明白了，出发！💪",
            "save_today" to "保存今天",
            "saving" to "保存中...",
            "saved" to "✅ 已保存",
            "language" to "语言",
            "select_language" to "选择语言",
            "change_password" to "🔒 修改密码",
            "current_password" to "当前密码",
            "new_password" to "新密码",
            "confirm_password" to "确认新密码",
            "update_password" to "更新密码",
            "ask_me" to "问我任何问题...",
            "send" to "发送",
            "profile" to "你的资料",
            "tell_us" to "告诉我们关于你的信息",
            "age" to "年龄",
            "weight" to "体重 (kg)",
            "height" to "身高 (cm)",
            "goal" to "🎯 目标",
            "activity_level" to "🏃 活动水平",
            "lose_weight" to "减重",
            "gain_muscle" to "增肌",
            "maintain_weight" to "保持体重",
            "improve_health" to "改善健康",
            "sedentary" to "久坐",
            "light" to "轻度",
            "moderate" to "中度",
            "active" to "活跃",
            "very_active" to "非常活跃",
            "loading_plan" to "正在加载你的计划...",
            "saved_plan" to "你保存的个性化计划",
            "update_profile" to "更新你的资料",
            "see_current_plan" to "← 查看当前计划",
            "point_at_food" to "对准食物",
            "nutritional_analysis" to "营养分析",
            "ai_result" to "AI结果",
            "save_to_log" to "保存到我的记录",
            "take_another_photo" to "再拍一张",
            "camera_permission_required" to "需要相机权限才能识别食物",
            "grant_permission" to "授予权限",
            "error_analyzing" to "分析出错",
            "xp_daily_limit_food" to "每天最多3张照片可获得XP",
            "chat_error" to "抱歉，发生了错误。请重试。",
            "level_beginner" to "初学者",
            "level_apprentice" to "学徒",
            "level_athlete" to "运动员",
            "level_expert" to "专家",
            "level_master" to "大师",
            "level" to "等级",
            "xp_to_next" to "距离下一级还需 {xp} XP",
            "max_level_reached" to "已达最高等级！🎉",
            "how_to_earn_xp" to "如何获得XP",
            "xp_action_progress" to "记录每日进度",
            "xp_action_plan" to "用AI生成计划",
            "xp_action_food" to "识别食物",
            "xp_action_chat" to "与营养师聊天",
            "xp_action_mood" to "记录心情",
            "all_levels" to "所有等级",
            "from_xp" to "从 {xp} XP 开始",
            "current" to "当前",
            "today_log" to "今日记录",
            "calories" to "卡路里",
            "xp_already_claimed_today" to "今日XP已领取",
            "weight_evolution" to "体重变化",
            "weight_short" to "体重",
            "daily_calories" to "每日卡路里",
            "no_data_yet" to "暂无数据。\n记录你的第一天吧！💪",
            "water_tracker" to "饮水跟踪",
            "food_history" to "饮食历史",
            "my_goals" to "我的目标",
            "achievements" to "成就",
            "exercise_log" to "运动记录",
            "weekly_report" to "每周报告",
            "bmr_calculator" to "BMR 计算器",
            "today_nutrition" to "今日营养",
            "quick_add" to "快速添加",
            "reset_today" to "重置今天",
            "now" to "现在",
            "start" to "起始",
            "current_goal" to "当前目标",
            "set_goal" to "设定目标",
            "save_goal" to "保存目标",
            "save" to "保存",
            "target_weight" to "目标体重 (kg)",
            "target_date_hint" to "目标日期",
            "days_left" to "还剩 {days} 天",
            "unlocked" to "已解锁",
            "no_food_yet" to "暂无饮食记录",
            "analyzing_week" to "正在分析你的一周...",
            "regenerate" to "重新生成",
            "no_week_data" to "需要至少7天的数据才能生成报告",
            "bmi" to "BMI",
            "bmi_underweight" to "偏瘦",
            "bmi_normal" to "健康",
            "bmi_overweight" to "超重",
            "bmi_obese" to "肥胖",
            "bmr_explain" to "静息代谢",
            "tdee_explain" to "每日总消耗",
            "recommended_targets" to "推荐目标",
            "protein" to "蛋白质",
            "carbs" to "碳水",
            "fat" to "脂肪",
            "water" to "饮水",
            "theme" to "主题",
            "theme_system" to "跟随系统",
            "theme_light" to "浅色",
            "theme_dark" to "深色",
            "notifications" to "通知",
            "notif_water_title" to "该喝水了",
            "notif_water_body" to "💧 喝一杯水，保持你的每日目标",
            "notif_water_desc" to "每3小时提醒一次",
            "notif_evening_title" to "记录你的一天",
            "notif_evening_body" to "🌙 记下体重、卡路里和心情",
            "notif_evening_desc" to "每晚 20:00",
            "bmr_subtitle" to "BMR、TDEE 和推荐营养素",
            "my_account" to "我的账号",
            "pwd_no_match" to "两次密码不一致",
            "pwd_too_short" to "密码至少需要 6 个字符",
            "pwd_update_failed" to "更新密码失败",
            "pwd_wrong_current" to "当前密码不正确",
            "choose_exercise" to "选择运动",
            "duration_min" to "时长 (分钟)",
            "recent_history" to "最近记录",
            "ex_walking" to "走路",
            "ex_running" to "跑步",
            "ex_cycling" to "骑行",
            "ex_swimming" to "游泳",
            "ex_yoga" to "瑜伽",
            "ex_gym" to "健身房",
            "ex_dance" to "跳舞",
            "ex_hiit" to "HIIT",
            "ach_first_plan_t" to "首个计划",
            "ach_first_plan_d" to "用 AI 生成你的第一个计划",
            "ach_first_food_t" to "首次扫描",
            "ach_first_food_d" to "识别你的第一份食物",
            "ach_first_chat_t" to "首次咨询",
            "ach_first_chat_d" to "与 AI 营养师聊天",
            "ach_first_mood_t" to "首次心情",
            "ach_first_mood_d" to "记录你的心情",
            "ach_first_water_t" to "首次饮水",
            "ach_first_water_d" to "记录第一杯水",
            "ach_first_exercise_t" to "首次运动",
            "ach_first_exercise_d" to "记录一次运动",
            "ach_streak3_t" to "3 天连胜",
            "ach_streak3_d" to "连续活跃 3 天",
            "ach_streak7_t" to "7 天连胜",
            "ach_streak7_d" to "整整一周不间断",
            "ach_streak30_t" to "30 天连胜",
            "ach_streak30_d" to "连续 30 天，无法阻挡",
            "ach_water_goal_t" to "饮水达标",
            "ach_water_goal_d" to "完成每日饮水目标",
            "ach_food10_t" to "10 餐",
            "ach_food10_d" to "扫描 10 份食物",
            "ach_food50_t" to "50 餐",
            "ach_food50_d" to "扫描 50 份食物",
            "ach_level3_t" to "运动员",
            "ach_level3_d" to "达到 3 级",
            "ach_level5_t" to "大师",
            "ach_level5_d" to "达到最高等级",
            "ach_goal_t" to "目标达成",
            "ach_goal_d" to "达到目标体重",
            "today" to "今天",
            "yesterday" to "昨天",
            "add_food" to "添加食物",
            "food_name" to "食物名称",
            "cancel" to "取消",
            "error_saving" to "保存失败：",
            "daily_challenge" to "今日挑战",
            "challenge_completed" to "挑战完成！",
            "mark_complete" to "标记完成",
            "ch_water_2l_t" to "喝够 2L 水",
            "ch_water_2l_d" to "今日至少 2000ml",
            "ch_scan_food_t" to "扫描 3 份食物",
            "ch_scan_food_d" to "今天用 AI 相机识别 3 顿饭",
            "ch_chat_t" to "向 AI 提问",
            "ch_chat_d" to "给 AI 营养师发一条消息",
            "ch_log_weight_t" to "称体重",
            "ch_log_weight_d" to "记录今日体重",
            "ch_exercise_t" to "运动 30 分钟",
            "ch_exercise_d" to "记录至少 30 分钟运动",
            "ch_mood_t" to "记录心情",
            "ch_mood_d" to "告诉 VitaAI 你今天感觉怎样",
            "ch_3_meals_t" to "三餐均衡",
            "ch_3_meals_d" to "记录早午晚三餐",
            "ch_no_sugar_t" to "今日不加糖",
            "ch_no_sugar_d" to "避免甜点和含糖饮料",
            "ch_walk_5k_t" to "走 5000 步",
            "ch_walk_5k_d" to "全天保持活动",
            "ch_protein_t" to "蛋白质达标",
            "ch_protein_d" to "达到每日蛋白质目标",
            "meal_planner" to "AI 餐食规划",
            "meal_planner_subtitle" to "根据你剩余的营养目标推荐三餐",
            "generating_meals" to "正在设计你的餐食...",
            "meal_breakfast" to "早餐",
            "meal_lunch" to "午餐",
            "meal_dinner" to "晚餐",
            "meal_snack" to "加餐",
            "log_meal" to "记录这餐",
            "favorites" to "收藏夹",
            "favorites_subtitle" to "常吃食物一键记录",
            "add_favorite" to "添加收藏",
            "log" to "记录",
            "no_favorites" to "还没有收藏",
            "monthly_stats" to "月度统计",
            "last_30_days" to "最近 30 天",
            "avg_calories" to "平均卡路里",
            "active_days" to "活跃天数",
            "total_exercise" to "运动总时长",
            "weight_change" to "体重变化",
            "vitals" to "健康指标",
            "vitals_subtitle" to "全面追踪你的健康",
            "log_today_vitals" to "记录今日",
            "body_fat_pct" to "体脂率 %",
            "bp_sys" to "收缩压",
            "bp_dia" to "舒张压",
            "sleep_hours" to "睡眠小时",
            "resting_hr" to "静息心率",
            "shopping_list" to "购物清单",
            "generating_list" to "正在生成清单...",
            "shop_cat_produce" to "🥬 果蔬",
            "shop_cat_protein" to "🥩 蛋白质",
            "shop_cat_dairy" to "🥛 乳制品",
            "shop_cat_grains" to "🌾 谷物",
            "shop_cat_pantry" to "🥫 调味/储存",
            "shop_cat_other" to "📦 其他",
            "recipes" to "AI 食谱",
            "recipes_subtitle" to "用家里现有的食材做菜",
            "available_ingredients" to "现有食材",
            "ingredients_example" to "例如：鸡肉、米饭、西兰花、大蒜、橄榄油",
            "generate_recipes" to "生成食谱 🍳",
            "generating_recipes" to "正在构思食谱...",
            "ingredients" to "食材",
            "steps" to "步骤",
            "view_recipe" to "查看食谱",
            "collapse" to "收起",
            "diff_easy" to "简单",
            "diff_medium" to "中等",
            "diff_hard" to "困难"
        ),
        "fr" to mapOf(
            "app_name" to "VitaAI",
            "login" to "Se connecter",
            "register" to "S'inscrire",
            "email" to "Email",
            "password" to "Mot de passe",
            "username" to "Nom d'utilisateur",
            "continue_google" to "Continuer avec Google",
            "no_account" to "Pas de compte ? S'inscrire",
            "have_account" to "Déjà un compte ? Se connecter",
            "forgot_password" to "Mot de passe oublié ?",
            "good_morning" to "Bonjour 👋",
            "daily_tip" to "💡 Conseil du jour",
            "today_mood" to "Humeur du jour",
            "quick_access" to "Accès rapide",
            "my_plan" to "Mon plan santé",
            "my_progress" to "Ma progression",
            "nutritionist_ia" to "Nutritionniste IA",
            "identify_food" to "Identifier l'aliment",
            "my_level" to "Mon niveau et XP",
            "more" to "Plus",
            "settings" to "Paramètres",
            "logout" to "Se déconnecter",
            "generate_plan" to "Générer mon plan IA 🤖",
            "update_plan" to "Mettre à jour le plan IA 🔄",
            "current_plan" to "🤖 Votre Plan Actuel",
            "diet_plan" to "🥗 Plan Alimentaire",
            "exercise_plan" to "💪 Plan d'Exercice",
            "update_my_plan" to "🔄 Mettre à jour mon plan",
            "back_to_home" to "✅ Retour à l'accueil",
            "generating_plan" to "Analyse de votre profil et génération\nde votre plan personnalisé...",
            "how_are_you" to "Comment vous sentez-vous aujourd'hui ?",
            "mood_affects" to "Votre humeur affecte votre nutrition",
            "get_recommendation" to "✨ Obtenir une recommandation personnalisée",
            "understood" to "Compris, allons-y ! 💪",
            "save_today" to "Enregistrer aujourd'hui",
            "saving" to "Enregistrement...",
            "saved" to "✅ Enregistré",
            "language" to "Langue",
            "select_language" to "Sélectionner la langue",
            "change_password" to "🔒 Changer le mot de passe",
            "current_password" to "Mot de passe actuel",
            "new_password" to "Nouveau mot de passe",
            "confirm_password" to "Confirmer le nouveau mot de passe",
            "update_password" to "Mettre à jour le mot de passe",
            "ask_me" to "Posez-moi une question...",
            "send" to "Envoyer",
            "profile" to "Votre profil",
            "tell_us" to "Parlez-nous de vous",
            "age" to "Âge",
            "weight" to "Poids (kg)",
            "height" to "Taille (cm)",
            "goal" to "🎯 Objectif",
            "activity_level" to "🏃 Niveau d'activité",
            "lose_weight" to "Perdre du poids",
            "gain_muscle" to "Gagner du muscle",
            "maintain_weight" to "Maintenir le poids",
            "improve_health" to "Améliorer la santé",
            "sedentary" to "Sédentaire",
            "light" to "Léger",
            "moderate" to "Modéré",
            "active" to "Actif",
            "very_active" to "Très actif",
            "loading_plan" to "Chargement de votre plan...",
            "saved_plan" to "Votre plan personnalisé enregistré",
            "update_profile" to "Mettre à jour votre profil",
            "see_current_plan" to "← Voir le plan actuel",
            "point_at_food" to "Pointez vers l'aliment",
            "nutritional_analysis" to "Analyse nutritionnelle",
            "ai_result" to "Résultat IA",
            "save_to_log" to "Enregistrer dans mon journal",
            "take_another_photo" to "Prendre une autre photo",
            "camera_permission_required" to "L'accès à la caméra est requis pour identifier les aliments",
            "grant_permission" to "Accorder la permission",
            "error_analyzing" to "Erreur d'analyse",
            "xp_daily_limit_food" to "maximum 3 photos avec XP par jour",
            "chat_error" to "Désolé, une erreur s'est produite. Veuillez réessayer.",
            "level_beginner" to "Débutant",
            "level_apprentice" to "Apprenti",
            "level_athlete" to "Athlète",
            "level_expert" to "Expert",
            "level_master" to "Maître",
            "level" to "Niveau",
            "xp_to_next" to "Encore {xp} XP pour le niveau suivant",
            "max_level_reached" to "Niveau maximum atteint ! 🎉",
            "how_to_earn_xp" to "Comment gagner de l'XP",
            "xp_action_progress" to "Enregistrer le progrès quotidien",
            "xp_action_plan" to "Générer un plan IA",
            "xp_action_food" to "Identifier un aliment",
            "xp_action_chat" to "Discuter avec le nutritionniste",
            "xp_action_mood" to "Enregistrer l'humeur",
            "all_levels" to "Tous les niveaux",
            "from_xp" to "À partir de {xp} XP",
            "current" to "ACTUEL",
            "today_log" to "Journal du jour",
            "calories" to "Calories",
            "xp_already_claimed_today" to "XP déjà réclamé aujourd'hui",
            "weight_evolution" to "Évolution du poids",
            "weight_short" to "Poids",
            "daily_calories" to "Calories quotidiennes",
            "no_data_yet" to "Pas encore de données.\nEnregistrez votre premier jour ! 💪",
            "water_tracker" to "Hydratation",
            "food_history" to "Historique alimentaire",
            "my_goals" to "Mes objectifs",
            "achievements" to "Succès",
            "exercise_log" to "Exercice",
            "weekly_report" to "Rapport hebdo",
            "bmr_calculator" to "Calculateur BMR",
            "today_nutrition" to "Nutrition du jour",
            "quick_add" to "Ajout rapide",
            "reset_today" to "Réinitialiser",
            "now" to "Actuel",
            "start" to "Départ",
            "current_goal" to "Objectif actuel",
            "set_goal" to "Définir l'objectif",
            "save_goal" to "Enregistrer l'objectif",
            "save" to "Enregistrer",
            "target_weight" to "Poids cible (kg)",
            "target_date_hint" to "Date cible",
            "days_left" to "{days} jours restants",
            "unlocked" to "Débloqués",
            "no_food_yet" to "Aucun aliment enregistré",
            "analyzing_week" to "Analyse de votre semaine...",
            "regenerate" to "Régénérer",
            "no_week_data" to "Enregistrez des données cette semaine pour générer le rapport",
            "bmi" to "IMC",
            "bmi_underweight" to "Insuffisance pondérale",
            "bmi_normal" to "Poids sain",
            "bmi_overweight" to "Surpoids",
            "bmi_obese" to "Obésité",
            "bmr_explain" to "Calories au repos",
            "tdee_explain" to "Dépense quotidienne",
            "recommended_targets" to "Objectifs recommandés",
            "protein" to "Protéines",
            "carbs" to "Glucides",
            "fat" to "Lipides",
            "water" to "Eau",
            "theme" to "Thème",
            "theme_system" to "Système",
            "theme_light" to "Clair",
            "theme_dark" to "Sombre",
            "notifications" to "Notifications",
            "notif_water_title" to "Hydratez-vous",
            "notif_water_body" to "💧 Buvez un verre d'eau pour rester sur la bonne voie",
            "notif_water_desc" to "Rappel toutes les 3 heures",
            "notif_evening_title" to "Notez votre journée",
            "notif_evening_body" to "🌙 Notez votre poids, calories et humeur",
            "notif_evening_desc" to "Chaque soir à 20h",
            "bmr_subtitle" to "BMR, TDEE et macros recommandés",
            "my_account" to "Mon compte",
            "pwd_no_match" to "Les mots de passe ne correspondent pas",
            "pwd_too_short" to "Le mot de passe doit contenir au moins 6 caractères",
            "pwd_update_failed" to "Échec de la mise à jour du mot de passe",
            "pwd_wrong_current" to "Mot de passe actuel incorrect",
            "choose_exercise" to "Choisir un exercice",
            "duration_min" to "Durée (min)",
            "recent_history" to "Historique récent",
            "ex_walking" to "Marche",
            "ex_running" to "Course",
            "ex_cycling" to "Vélo",
            "ex_swimming" to "Natation",
            "ex_yoga" to "Yoga",
            "ex_gym" to "Salle de sport",
            "ex_dance" to "Danse",
            "ex_hiit" to "HIIT",
            "ach_first_plan_t" to "Premier plan",
            "ach_first_plan_d" to "Générez votre premier plan IA",
            "ach_first_food_t" to "Premier scan",
            "ach_first_food_d" to "Identifiez votre premier aliment",
            "ach_first_chat_t" to "Première discussion",
            "ach_first_chat_d" to "Parlez au nutritionniste IA",
            "ach_first_mood_t" to "Première humeur",
            "ach_first_mood_d" to "Enregistrez votre humeur",
            "ach_first_water_t" to "Hydratation",
            "ach_first_water_d" to "Enregistrez votre premier verre d'eau",
            "ach_first_exercise_t" to "Premier entraînement",
            "ach_first_exercise_d" to "Enregistrez une séance",
            "ach_streak3_t" to "Série de 3",
            "ach_streak3_d" to "3 jours d'affilée actif",
            "ach_streak7_t" to "Série de 7",
            "ach_streak7_d" to "Une semaine entière sans manquer",
            "ach_streak30_t" to "Série de 30",
            "ach_streak30_d" to "30 jours d'affilée. Imparable",
            "ach_water_goal_t" to "Objectif eau",
            "ach_water_goal_d" to "Atteignez votre objectif quotidien d'eau",
            "ach_food10_t" to "10 repas",
            "ach_food10_d" to "Scannez 10 aliments",
            "ach_food50_t" to "50 repas",
            "ach_food50_d" to "Scannez 50 aliments",
            "ach_level3_t" to "Athlète",
            "ach_level3_d" to "Atteignez le niveau 3",
            "ach_level5_t" to "Maître",
            "ach_level5_d" to "Atteignez le niveau max",
            "ach_goal_t" to "Objectif atteint",
            "ach_goal_d" to "Atteignez votre poids cible",
            "today" to "Aujourd'hui",
            "yesterday" to "Hier",
            "add_food" to "Ajouter un aliment",
            "food_name" to "Nom de l'aliment",
            "cancel" to "Annuler",
            "error_saving" to "Erreur sauvegarde : ",
            "daily_challenge" to "Défi du jour",
            "challenge_completed" to "Défi accompli !",
            "mark_complete" to "Marquer comme fait",
            "ch_water_2l_t" to "Boire 2L d'eau",
            "ch_water_2l_d" to "Atteindre au moins 2000ml aujourd'hui",
            "ch_scan_food_t" to "Scanner 3 aliments",
            "ch_scan_food_d" to "Utilise la caméra IA sur 3 repas aujourd'hui",
            "ch_chat_t" to "Pose une question à l'IA",
            "ch_chat_d" to "Envoie un message au nutritionniste IA",
            "ch_log_weight_t" to "Pèse-toi",
            "ch_log_weight_d" to "Enregistre ton poids du jour",
            "ch_exercise_t" to "30 minutes de mouvement",
            "ch_exercise_d" to "Enregistre au moins 30 min d'exercice",
            "ch_mood_t" to "Note ton humeur",
            "ch_mood_d" to "Dis à VitaAI comment tu te sens",
            "ch_3_meals_t" to "3 repas équilibrés",
            "ch_3_meals_d" to "Petit-déj, déjeuner et dîner enregistrés",
            "ch_no_sugar_t" to "Journée sans sucre ajouté",
            "ch_no_sugar_d" to "Évite les sucreries et boissons sucrées",
            "ch_walk_5k_t" to "Marche 5 000 pas",
            "ch_walk_5k_d" to "Reste actif toute la journée",
            "ch_protein_t" to "Atteins ta protéine",
            "ch_protein_d" to "Atteins ton objectif quotidien de protéines",
            "meal_planner" to "Planificateur IA",
            "meal_planner_subtitle" to "Repas adaptés à tes macros restants",
            "generating_meals" to "Conception de tes repas...",
            "meal_breakfast" to "Petit-déjeuner",
            "meal_lunch" to "Déjeuner",
            "meal_dinner" to "Dîner",
            "meal_snack" to "Collation",
            "log_meal" to "Enregistrer le repas",
            "favorites" to "Favoris",
            "favorites_subtitle" to "Repas fréquents en un clic",
            "add_favorite" to "Ajouter aux favoris",
            "log" to "Enregistrer",
            "no_favorites" to "Aucun favori pour l'instant",
            "monthly_stats" to "Stats mensuelles",
            "last_30_days" to "30 derniers jours",
            "avg_calories" to "kcal moyen",
            "active_days" to "Jours actifs",
            "total_exercise" to "Exercice total",
            "weight_change" to "Variation de poids",
            "vitals" to "Constantes vitales",
            "vitals_subtitle" to "Suivi complet de ta santé",
            "log_today_vitals" to "Enregistrer aujourd'hui",
            "body_fat_pct" to "% masse grasse",
            "bp_sys" to "Systolique",
            "bp_dia" to "Diastolique",
            "sleep_hours" to "Heures de sommeil",
            "resting_hr" to "FC au repos",
            "shopping_list" to "Liste de courses",
            "generating_list" to "Génération de ta liste...",
            "shop_cat_produce" to "🥬 Fruits et légumes",
            "shop_cat_protein" to "🥩 Protéines",
            "shop_cat_dairy" to "🥛 Produits laitiers",
            "shop_cat_grains" to "🌾 Céréales",
            "shop_cat_pantry" to "🥫 Épicerie",
            "shop_cat_other" to "📦 Autres",
            "recipes" to "Recettes IA",
            "recipes_subtitle" to "Cuisine avec ce que tu as à la maison",
            "available_ingredients" to "Ingrédients disponibles",
            "ingredients_example" to "ex: poulet, riz, brocoli, ail, huile d'olive",
            "generate_recipes" to "Générer des recettes 🍳",
            "generating_recipes" to "Réflexion en cours...",
            "ingredients" to "Ingrédients",
            "steps" to "Étapes",
            "view_recipe" to "Voir la recette",
            "collapse" to "Réduire",
            "diff_easy" to "Facile",
            "diff_medium" to "Moyen",
            "diff_hard" to "Difficile"
        ),
        "pt" to mapOf(
            "app_name" to "VitaAI",
            "login" to "Entrar",
            "register" to "Registrar",
            "email" to "Email",
            "password" to "Senha",
            "username" to "Nome de usuário",
            "continue_google" to "Continuar com Google",
            "no_account" to "Não tem conta? Registre-se",
            "have_account" to "Já tem conta? Entre",
            "forgot_password" to "Esqueceu a senha?",
            "good_morning" to "Bom dia 👋",
            "daily_tip" to "💡 Dica do dia",
            "today_mood" to "Humor de hoje",
            "quick_access" to "Acesso rápido",
            "my_plan" to "Meu plano de saúde",
            "my_progress" to "Meu progresso",
            "nutritionist_ia" to "Nutricionista IA",
            "identify_food" to "Identificar alimento",
            "my_level" to "Meu nível e XP",
            "more" to "Mais",
            "settings" to "Configurações",
            "logout" to "Sair",
            "generate_plan" to "Gerar meu plano com IA 🤖",
            "update_plan" to "Atualizar plano com IA 🔄",
            "current_plan" to "🤖 Seu Plano Atual",
            "diet_plan" to "🥗 Plano Alimentar",
            "exercise_plan" to "💪 Plano de Exercícios",
            "update_my_plan" to "🔄 Atualizar meu plano",
            "back_to_home" to "✅ Voltar ao início",
            "generating_plan" to "Analisando seu perfil e gerando\nseu plano personalizado...",
            "how_are_you" to "Como você está hoje?",
            "mood_affects" to "Seu humor afeta sua nutrição",
            "get_recommendation" to "✨ Obter recomendação personalizada",
            "understood" to "Entendido, vamos! 💪",
            "save_today" to "Salvar hoje",
            "saving" to "Salvando...",
            "saved" to "✅ Salvo",
            "language" to "Idioma",
            "select_language" to "Selecionar idioma",
            "change_password" to "🔒 Alterar senha",
            "current_password" to "Senha atual",
            "new_password" to "Nova senha",
            "confirm_password" to "Confirmar nova senha",
            "update_password" to "Atualizar senha",
            "ask_me" to "Me pergunte algo...",
            "send" to "Enviar",
            "profile" to "Seu perfil",
            "tell_us" to "Conte-nos sobre você",
            "age" to "Idade",
            "weight" to "Peso (kg)",
            "height" to "Altura (cm)",
            "goal" to "🎯 Objetivo",
            "activity_level" to "🏃 Nível de atividade",
            "lose_weight" to "Perder peso",
            "gain_muscle" to "Ganhar músculo",
            "maintain_weight" to "Manter peso",
            "improve_health" to "Melhorar saúde",
            "sedentary" to "Sedentário",
            "light" to "Leve",
            "moderate" to "Moderado",
            "active" to "Ativo",
            "very_active" to "Muito ativo",
            "loading_plan" to "Carregando seu plano...",
            "saved_plan" to "Seu plano personalizado salvo",
            "update_profile" to "Atualizar seu perfil",
            "see_current_plan" to "← Ver plano atual",
            "point_at_food" to "Aponte para o alimento",
            "nutritional_analysis" to "Análise nutricional",
            "ai_result" to "Resultado IA",
            "save_to_log" to "Salvar no meu registro",
            "take_another_photo" to "Tirar outra foto",
            "camera_permission_required" to "O acesso à câmera é necessário para identificar alimentos",
            "grant_permission" to "Conceder permissão",
            "error_analyzing" to "Erro ao analisar",
            "xp_daily_limit_food" to "máximo 3 fotos com XP por dia",
            "chat_error" to "Desculpe, houve um erro. Por favor, tente novamente.",
            "level_beginner" to "Iniciante",
            "level_apprentice" to "Aprendiz",
            "level_athlete" to "Atleta",
            "level_expert" to "Especialista",
            "level_master" to "Mestre",
            "level" to "Nível",
            "xp_to_next" to "Faltam {xp} XP para o próximo nível",
            "max_level_reached" to "Nível máximo alcançado! 🎉",
            "how_to_earn_xp" to "Como ganhar XP",
            "xp_action_progress" to "Registrar progresso diário",
            "xp_action_plan" to "Gerar plano com IA",
            "xp_action_food" to "Identificar alimento",
            "xp_action_chat" to "Conversar com nutricionista",
            "xp_action_mood" to "Registrar humor",
            "all_levels" to "Todos os níveis",
            "from_xp" to "A partir de {xp} XP",
            "current" to "ATUAL",
            "today_log" to "Registro de hoje",
            "calories" to "Calorias",
            "xp_already_claimed_today" to "XP já reclamado hoje",
            "weight_evolution" to "Evolução do peso",
            "weight_short" to "Peso",
            "daily_calories" to "Calorias diárias",
            "no_data_yet" to "Ainda sem dados.\nRegistre seu primeiro dia! 💪",
            "water_tracker" to "Hidratação",
            "food_history" to "Histórico de comidas",
            "my_goals" to "Meus objetivos",
            "achievements" to "Conquistas",
            "exercise_log" to "Exercício",
            "weekly_report" to "Relatório semanal",
            "bmr_calculator" to "Calculadora BMR",
            "today_nutrition" to "Nutrição de hoje",
            "quick_add" to "Adicionar rápido",
            "reset_today" to "Resetar hoje",
            "now" to "Agora",
            "start" to "Início",
            "current_goal" to "Objetivo atual",
            "set_goal" to "Definir objetivo",
            "save_goal" to "Salvar objetivo",
            "save" to "Salvar",
            "target_weight" to "Peso alvo (kg)",
            "target_date_hint" to "Data alvo",
            "days_left" to "Faltam {days} dias",
            "unlocked" to "Desbloqueadas",
            "no_food_yet" to "Nenhuma refeição registrada",
            "analyzing_week" to "Analisando sua semana...",
            "regenerate" to "Regenerar",
            "no_week_data" to "Registre dados nesta semana para gerar o relatório",
            "bmi" to "IMC",
            "bmi_underweight" to "Abaixo do peso",
            "bmi_normal" to "Peso saudável",
            "bmi_overweight" to "Sobrepeso",
            "bmi_obese" to "Obesidade",
            "bmr_explain" to "Calorias em repouso",
            "tdee_explain" to "Gasto diário total",
            "recommended_targets" to "Metas recomendadas",
            "protein" to "Proteína",
            "carbs" to "Carboidratos",
            "fat" to "Gordura",
            "water" to "Água",
            "theme" to "Tema",
            "theme_system" to "Sistema",
            "theme_light" to "Claro",
            "theme_dark" to "Escuro",
            "notifications" to "Notificações",
            "notif_water_title" to "Hora de se hidratar",
            "notif_water_body" to "💧 Beba um copo de água e mantenha sua meta",
            "notif_water_desc" to "Lembretes a cada 3 horas",
            "notif_evening_title" to "Registre seu dia",
            "notif_evening_body" to "🌙 Anote peso, calorias e humor",
            "notif_evening_desc" to "Toda noite às 20:00",
            "bmr_subtitle" to "BMR, TDEE e macros recomendados",
            "my_account" to "Minha conta",
            "pwd_no_match" to "As senhas não coincidem",
            "pwd_too_short" to "A senha deve ter pelo menos 6 caracteres",
            "pwd_update_failed" to "Falha ao atualizar a senha",
            "pwd_wrong_current" to "Senha atual incorreta",
            "choose_exercise" to "Escolha um exercício",
            "duration_min" to "Duração (min)",
            "recent_history" to "Histórico recente",
            "ex_walking" to "Caminhada",
            "ex_running" to "Corrida",
            "ex_cycling" to "Ciclismo",
            "ex_swimming" to "Natação",
            "ex_yoga" to "Yoga",
            "ex_gym" to "Academia",
            "ex_dance" to "Dança",
            "ex_hiit" to "HIIT",
            "ach_first_plan_t" to "Primeiro plano",
            "ach_first_plan_d" to "Gere seu primeiro plano com IA",
            "ach_first_food_t" to "Primeiro scan",
            "ach_first_food_d" to "Identifique seu primeiro alimento",
            "ach_first_chat_t" to "Primeira conversa",
            "ach_first_chat_d" to "Fale com o nutricionista IA",
            "ach_first_mood_t" to "Primeiro humor",
            "ach_first_mood_d" to "Registre como você se sente",
            "ach_first_water_t" to "Hidratação",
            "ach_first_water_d" to "Registre seu primeiro copo de água",
            "ach_first_exercise_t" to "Primeiro treino",
            "ach_first_exercise_d" to "Registre uma sessão",
            "ach_streak3_t" to "Sequência de 3",
            "ach_streak3_d" to "3 dias seguidos ativo",
            "ach_streak7_t" to "Sequência de 7",
            "ach_streak7_d" to "Uma semana inteira sem falhar",
            "ach_streak30_t" to "Sequência de 30",
            "ach_streak30_d" to "30 dias seguidos. Imparável",
            "ach_water_goal_t" to "Meta de água",
            "ach_water_goal_d" to "Cumpra sua meta diária de água",
            "ach_food10_t" to "10 refeições",
            "ach_food10_d" to "Escaneie 10 alimentos",
            "ach_food50_t" to "50 refeições",
            "ach_food50_d" to "Escaneie 50 alimentos",
            "ach_level3_t" to "Atleta",
            "ach_level3_d" to "Alcance o nível 3",
            "ach_level5_t" to "Mestre",
            "ach_level5_d" to "Alcance o nível máximo",
            "ach_goal_t" to "Meta atingida",
            "ach_goal_d" to "Atinja seu peso alvo",
            "today" to "Hoje",
            "yesterday" to "Ontem",
            "add_food" to "Adicionar comida",
            "food_name" to "Nome do alimento",
            "cancel" to "Cancelar",
            "error_saving" to "Erro ao salvar: ",
            "daily_challenge" to "Desafio do dia",
            "challenge_completed" to "Desafio concluído!",
            "mark_complete" to "Marcar como feito",
            "ch_water_2l_t" to "Beba 2L de água",
            "ch_water_2l_d" to "Alcance pelo menos 2000ml hoje",
            "ch_scan_food_t" to "Escaneie 3 alimentos",
            "ch_scan_food_d" to "Use a câmera IA em 3 refeições hoje",
            "ch_chat_t" to "Pergunte à IA",
            "ch_chat_d" to "Envie uma mensagem ao nutricionista IA",
            "ch_log_weight_t" to "Pese-se",
            "ch_log_weight_d" to "Registre seu peso de hoje",
            "ch_exercise_t" to "30 minutos de movimento",
            "ch_exercise_d" to "Registre pelo menos 30 min de exercício",
            "ch_mood_t" to "Registre seu humor",
            "ch_mood_d" to "Conte ao VitaAI como você está",
            "ch_3_meals_t" to "3 refeições balanceadas",
            "ch_3_meals_d" to "Café, almoço e jantar registrados",
            "ch_no_sugar_t" to "Dia sem açúcar adicionado",
            "ch_no_sugar_d" to "Evite doces e bebidas açucaradas",
            "ch_walk_5k_t" to "Caminhe 5000 passos",
            "ch_walk_5k_d" to "Mantenha-se ativo o dia todo",
            "ch_protein_t" to "Alcance sua proteína",
            "ch_protein_d" to "Atinja sua meta diária de proteína",
            "meal_planner" to "Planejador IA",
            "meal_planner_subtitle" to "Refeições adaptadas aos seus macros restantes",
            "generating_meals" to "Planejando suas refeições...",
            "meal_breakfast" to "Café da manhã",
            "meal_lunch" to "Almoço",
            "meal_dinner" to "Jantar",
            "meal_snack" to "Lanche",
            "log_meal" to "Registrar refeição",
            "favorites" to "Favoritos",
            "favorites_subtitle" to "Refeições frequentes com um toque",
            "add_favorite" to "Adicionar favorito",
            "log" to "Registrar",
            "no_favorites" to "Sem favoritos ainda",
            "monthly_stats" to "Estatísticas mensais",
            "last_30_days" to "Últimos 30 dias",
            "avg_calories" to "kcal média",
            "active_days" to "Dias ativos",
            "total_exercise" to "Exercício total",
            "weight_change" to "Variação de peso",
            "vitals" to "Sinais vitais",
            "vitals_subtitle" to "Acompanhe toda sua saúde",
            "log_today_vitals" to "Registrar hoje",
            "body_fat_pct" to "% gordura corporal",
            "bp_sys" to "Sistólica",
            "bp_dia" to "Diastólica",
            "sleep_hours" to "Horas de sono",
            "resting_hr" to "FC repouso",
            "shopping_list" to "Lista de compras",
            "generating_list" to "Gerando sua lista...",
            "shop_cat_produce" to "🥬 Hortifruti",
            "shop_cat_protein" to "🥩 Proteínas",
            "shop_cat_dairy" to "🥛 Laticínios",
            "shop_cat_grains" to "🌾 Grãos",
            "shop_cat_pantry" to "🥫 Despensa",
            "shop_cat_other" to "📦 Outros",
            "recipes" to "Receitas IA",
            "recipes_subtitle" to "Cozinhe com o que tem em casa",
            "available_ingredients" to "Ingredientes disponíveis",
            "ingredients_example" to "ex: frango, arroz, brócolis, alho, azeite",
            "generate_recipes" to "Gerar receitas 🍳",
            "generating_recipes" to "Pensando em receitas...",
            "ingredients" to "Ingredientes",
            "steps" to "Passos",
            "view_recipe" to "Ver receita",
            "collapse" to "Recolher",
            "diff_easy" to "Fácil",
            "diff_medium" to "Médio",
            "diff_hard" to "Difícil"
        )
    )
}